import { defineConfig } from 'vite';

/**
 * Inject /yurui-env.js before config.js so AppConfig can read window.__YURUI_ENV__.
 * English: public/yurui-env.js is generated by scripts/write-yurui-env.mjs
 */
function injectYuruiEnvScript() {
  const tag = '<script src="/yurui-env.js"></script>\n';
  return {
    name: 'inject-yurui-env-script',
    transformIndexHtml(html) {
      if (html.includes('/yurui-env.js')) {
        return html;
      }
      if (html.includes('/storefront/js/config.js')) {
        return html.replace(
          /<script([^>]*)\ssrc="\/storefront\/js\/config\.js"/,
          `${tag}<script$1 src="/storefront/js/config.js"`
        );
      }
      return html;
    },
  };
}

/**
 * Defines every static HTML page plus the SCSS entry that Vite should process.
 * Main store pages live under storefront/pages/ after B1 layout.
 */
export default defineConfig({
  appType: 'mpa',
  plugins: [injectYuruiEnvScript()],
  css: {
    devSourcemap: true,
  },
  build: {
    assetsInlineLimit: 4096,
    rollupOptions: {
      input: {
        index: 'index.html',
        home: 'storefront/pages/home.html',
        products: 'storefront/pages/products.html',
        productDetail: 'storefront/pages/product-detail.html',
        cart: 'storefront/pages/cart.html',
        checkout: 'storefront/pages/checkout.html',
        checkoutSuccess: 'storefront/pages/checkout-success.html',
        bookingSuccess: 'booking/pages/booking-success.html',
        memberCenter: 'storefront/pages/member-center.html',
        blog: 'storefront/pages/blog.html',
        blogDetail: 'storefront/pages/blog-detail.html',
        branches: 'storefront/pages/branches.html',
        faq: 'storefront/pages/faq.html',
        privacy: 'storefront/pages/privacy.html',
        terms: 'storefront/pages/terms.html',
        styles: 'src/styles.js',
      },
    },
  },
});
